# database config file

development:
    adapter: mongodb
    host: localhost
    port: 27017
    name: cforum_development

test:
    adapter: mongodb
    host: localhost
    port: 27017
    name: cforum_test

production:
    adapter: mongodb
    host: localhost
    port: 27017
    name: cforum_production

