name: Elixir CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres

    container:
      image: elixir:latest
      env:
        MIX_ENV: test

    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          apt update
          apt install -y postgresql-client
      - name: Run Tests
        run: |
          MIX_ENV=test mix ecto.reset
          mix test
        env:
          DB_HOST: postgres
          DB_USER: postgres
          DB_PASS: postgres
